"""Initial migration.

Revision ID: 86e188fc1070
Revises: 
Create Date: 2020-05-31 09:07:26.569902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e188fc1070'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segment_effort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('effort_count', sa.Integer(), nullable=True),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('athlete_count', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_id', 'date')
    )
    op.create_index(op.f('ix_segment_effort_date'), 'segment_effort', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segment_effort_date'), table_name='segment_effort')
    op.drop_table('segment_effort')
    op.drop_table('segment')
    # ### end Alembic commands ###
